### ISSUE TITLE
question

### ISSUE THREAD

**Issue by DrMadhuC** [supratimdasinfo/magnetocaloric.mcepy#1]
Dear Supratim Das

Thanks for your code on magnetocalorics using python program, it is time saver for sure.

Please share the procedure to run the same program on windows OS

Thank you

**Comment by supratimdasinfo** [comment]
Please follow this link (1st link and 2nd link) for a detailed tutorial on
how to use the Magnetocaloric Calculator (Portable Windows GUI executable
file). Use the 3rd link to download the zip file containing the above
mentioned software. Please follow the readme provided in the Gdrive folder
for the password of the zip file. Please acknowledge generously.

https://youtu.be/DmP6neZzv4A (Presentation)
https://youtu.be/c-9Yi7mxIoQ (Video tutorial)
https://drive.google.com/drive/folders/1qHrjOKbnDXf2PmNZaRKuHkwO3ScHDyY3?usp=drive_link
(File download link)
